namespace тренировка
{
    partial class FormSPD
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormSPD));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bnfGradPnlTitle = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.lblUserName = new System.Windows.Forms.Label();
            this.buttonClose = new System.Windows.Forms.Button();
            this.lblTitle = new System.Windows.Forms.Label();
            this.txtSearchSite = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BnfBtnPersData = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BnfBtnPass = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BnfBtnSites = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.DGV = new System.Windows.Forms.DataGridView();
            this.lblWelcome = new System.Windows.Forms.Label();
            this.bnBtnPassCheck = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bnfBtnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtSearchPass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bnfGradPnlTitle.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DGV)).BeginInit();
            this.SuspendLayout();
            // 
            // bnfGradPnlTitle
            // 
            this.bnfGradPnlTitle.BackColor = System.Drawing.Color.Transparent;
            this.bnfGradPnlTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bnfGradPnlTitle.BackgroundImage")));
            this.bnfGradPnlTitle.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bnfGradPnlTitle.BorderRadius = 1;
            this.bnfGradPnlTitle.Controls.Add(this.lblUserName);
            this.bnfGradPnlTitle.Controls.Add(this.buttonClose);
            this.bnfGradPnlTitle.Controls.Add(this.lblTitle);
            this.bnfGradPnlTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.bnfGradPnlTitle.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfGradPnlTitle.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfGradPnlTitle.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(16)))), ((int)(((byte)(221)))));
            this.bnfGradPnlTitle.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(16)))), ((int)(((byte)(221)))));
            this.bnfGradPnlTitle.Location = new System.Drawing.Point(0, 0);
            this.bnfGradPnlTitle.Name = "bnfGradPnlTitle";
            this.bnfGradPnlTitle.Quality = 10;
            this.bnfGradPnlTitle.Size = new System.Drawing.Size(1000, 45);
            this.bnfGradPnlTitle.TabIndex = 0;
            // 
            // lblUserName
            // 
            this.lblUserName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblUserName.Font = new System.Drawing.Font("Proxima Nova ExCn Lt", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.lblUserName.ForeColor = System.Drawing.Color.White;
            this.lblUserName.Location = new System.Drawing.Point(250, 0);
            this.lblUserName.Name = "lblUserName";
            this.lblUserName.Size = new System.Drawing.Size(500, 45);
            this.lblUserName.TabIndex = 38;
            this.lblUserName.Text = "UserName";
            this.lblUserName.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // buttonClose
            // 
            this.buttonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClose.BackgroundImage")));
            this.buttonClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.buttonClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonClose.FlatAppearance.BorderSize = 0;
            this.buttonClose.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.buttonClose.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.buttonClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonClose.Location = new System.Drawing.Point(975, 10);
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.Size = new System.Drawing.Size(17, 17);
            this.buttonClose.TabIndex = 37;
            this.buttonClose.UseVisualStyleBackColor = true;
            this.buttonClose.Click += new System.EventHandler(this.ButtonClose_Click_1);
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(10, 10);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(133, 23);
            this.lblTitle.TabIndex = 1;
            this.lblTitle.Text = "Save Personal Data";
            // 
            // txtSearchSite
            // 
            this.txtSearchSite.AcceptsReturn = false;
            this.txtSearchSite.AcceptsTab = false;
            this.txtSearchSite.AnimationSpeed = 200;
            this.txtSearchSite.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearchSite.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearchSite.BackColor = System.Drawing.Color.Transparent;
            this.txtSearchSite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearchSite.BackgroundImage")));
            this.txtSearchSite.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(16)))), ((int)(((byte)(221)))));
            this.txtSearchSite.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearchSite.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchSite.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchSite.BorderRadius = 35;
            this.txtSearchSite.BorderThickness = 1;
            this.txtSearchSite.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearchSite.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchSite.DefaultFont = new System.Drawing.Font("Proxima Nova Cn Lt", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.txtSearchSite.DefaultText = "";
            this.txtSearchSite.FillColor = System.Drawing.Color.White;
            this.txtSearchSite.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchSite.HideSelection = true;
            this.txtSearchSite.IconLeft = null;
            this.txtSearchSite.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchSite.IconPadding = 10;
            this.txtSearchSite.IconRight = null;
            this.txtSearchSite.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchSite.Lines = new string[0];
            this.txtSearchSite.Location = new System.Drawing.Point(10, 70);
            this.txtSearchSite.MaxLength = 32767;
            this.txtSearchSite.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearchSite.Modified = false;
            this.txtSearchSite.Multiline = false;
            this.txtSearchSite.Name = "txtSearchSite";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(116)))), ((int)(((byte)(204)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchSite.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearchSite.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchSite.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchSite.OnIdleState = stateProperties4;
            this.txtSearchSite.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearchSite.PasswordChar = '\0';
            this.txtSearchSite.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchSite.PlaceholderText = "Поиск";
            this.txtSearchSite.ReadOnly = false;
            this.txtSearchSite.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearchSite.SelectedText = "";
            this.txtSearchSite.SelectionLength = 0;
            this.txtSearchSite.SelectionStart = 0;
            this.txtSearchSite.ShortcutsEnabled = true;
            this.txtSearchSite.Size = new System.Drawing.Size(260, 40);
            this.txtSearchSite.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearchSite.TabIndex = 1;
            this.txtSearchSite.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearchSite.TextMarginBottom = 0;
            this.txtSearchSite.TextMarginLeft = 3;
            this.txtSearchSite.TextMarginTop = 0;
            this.txtSearchSite.TextPlaceholder = "Поиск";
            this.txtSearchSite.UseSystemPasswordChar = false;
            this.txtSearchSite.Visible = false;
            this.txtSearchSite.WordWrap = true;
            this.txtSearchSite.TextChange += new System.EventHandler(this.TxtSearch_TextChange);
            this.txtSearchSite.TextChanged += new System.EventHandler(this.TxtSearch_TextChanged);
            // 
            // BnfBtnPersData
            // 
            this.BnfBtnPersData.AllowAnimations = true;
            this.BnfBtnPersData.AllowMouseEffects = true;
            this.BnfBtnPersData.AllowToggling = true;
            this.BnfBtnPersData.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BnfBtnPersData.AnimationSpeed = 200;
            this.BnfBtnPersData.AutoGenerateColors = false;
            this.BnfBtnPersData.AutoRoundBorders = false;
            this.BnfBtnPersData.AutoSizeLeftIcon = true;
            this.BnfBtnPersData.AutoSizeRightIcon = true;
            this.BnfBtnPersData.BackColor = System.Drawing.Color.Transparent;
            this.BnfBtnPersData.BackColor1 = System.Drawing.Color.White;
            this.BnfBtnPersData.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BnfBtnPersData.BackgroundImage")));
            this.BnfBtnPersData.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPersData.ButtonText = "Персональные данные";
            this.BnfBtnPersData.ButtonTextMarginLeft = 0;
            this.BnfBtnPersData.ColorContrastOnClick = 45;
            this.BnfBtnPersData.ColorContrastOnHover = 45;
            this.BnfBtnPersData.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = false;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = false;
            this.BnfBtnPersData.CustomizableEdges = borderEdges1;
            this.BnfBtnPersData.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BnfBtnPersData.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.DisabledForecolor = System.Drawing.Color.White;
            this.BnfBtnPersData.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BnfBtnPersData.Font = new System.Drawing.Font("Proxima Nova Cn Lt", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.BnfBtnPersData.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BnfBtnPersData.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.BnfBtnPersData.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BnfBtnPersData.IconMarginLeft = 11;
            this.BnfBtnPersData.IconPadding = 10;
            this.BnfBtnPersData.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BnfBtnPersData.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.BnfBtnPersData.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BnfBtnPersData.IconSize = 25;
            this.BnfBtnPersData.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.IdleBorderRadius = 35;
            this.BnfBtnPersData.IdleBorderThickness = 1;
            this.BnfBtnPersData.IdleFillColor = System.Drawing.Color.White;
            this.BnfBtnPersData.IdleIconLeftImage = null;
            this.BnfBtnPersData.IdleIconRightImage = null;
            this.BnfBtnPersData.IndicateFocus = true;
            this.BnfBtnPersData.Location = new System.Drawing.Point(680, 70);
            this.BnfBtnPersData.Name = "BnfBtnPersData";
            this.BnfBtnPersData.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnDisabledState.BorderRadius = 35;
            this.BnfBtnPersData.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPersData.OnDisabledState.BorderThickness = 1;
            this.BnfBtnPersData.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPersData.OnDisabledState.IconLeftImage = null;
            this.BnfBtnPersData.OnDisabledState.IconRightImage = null;
            this.BnfBtnPersData.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.onHoverState.BorderRadius = 35;
            this.BnfBtnPersData.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPersData.onHoverState.BorderThickness = 1;
            this.BnfBtnPersData.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPersData.onHoverState.IconLeftImage = null;
            this.BnfBtnPersData.onHoverState.IconRightImage = null;
            this.BnfBtnPersData.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnIdleState.BorderRadius = 35;
            this.BnfBtnPersData.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPersData.OnIdleState.BorderThickness = 1;
            this.BnfBtnPersData.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BnfBtnPersData.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnIdleState.IconLeftImage = null;
            this.BnfBtnPersData.OnIdleState.IconRightImage = null;
            this.BnfBtnPersData.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnPressedState.BorderRadius = 35;
            this.BnfBtnPersData.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPersData.OnPressedState.BorderThickness = 1;
            this.BnfBtnPersData.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPersData.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPersData.OnPressedState.IconLeftImage = null;
            this.BnfBtnPersData.OnPressedState.IconRightImage = null;
            this.BnfBtnPersData.Size = new System.Drawing.Size(150, 36);
            this.BnfBtnPersData.TabIndex = 3;
            this.BnfBtnPersData.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BnfBtnPersData.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BnfBtnPersData.TextMarginLeft = 0;
            this.BnfBtnPersData.TextPadding = new System.Windows.Forms.Padding(0);
            this.BnfBtnPersData.UseDefaultRadiusAndThickness = true;
            this.BnfBtnPersData.Click += new System.EventHandler(this.BnfBtnPersData_Click);
            // 
            // BnfBtnPass
            // 
            this.BnfBtnPass.AllowAnimations = true;
            this.BnfBtnPass.AllowMouseEffects = true;
            this.BnfBtnPass.AllowToggling = true;
            this.BnfBtnPass.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BnfBtnPass.AnimationSpeed = 200;
            this.BnfBtnPass.AutoGenerateColors = false;
            this.BnfBtnPass.AutoRoundBorders = false;
            this.BnfBtnPass.AutoSizeLeftIcon = true;
            this.BnfBtnPass.AutoSizeRightIcon = true;
            this.BnfBtnPass.BackColor = System.Drawing.Color.Transparent;
            this.BnfBtnPass.BackColor1 = System.Drawing.Color.White;
            this.BnfBtnPass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BnfBtnPass.BackgroundImage")));
            this.BnfBtnPass.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPass.ButtonText = "Пароли";
            this.BnfBtnPass.ButtonTextMarginLeft = 0;
            this.BnfBtnPass.ColorContrastOnClick = 45;
            this.BnfBtnPass.ColorContrastOnHover = 45;
            this.BnfBtnPass.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = false;
            borderEdges2.BottomRight = false;
            borderEdges2.TopLeft = false;
            borderEdges2.TopRight = false;
            this.BnfBtnPass.CustomizableEdges = borderEdges2;
            this.BnfBtnPass.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BnfBtnPass.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.DisabledForecolor = System.Drawing.Color.White;
            this.BnfBtnPass.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BnfBtnPass.Font = new System.Drawing.Font("Proxima Nova Cn Lt", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.BnfBtnPass.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BnfBtnPass.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BnfBtnPass.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BnfBtnPass.IconMarginLeft = 11;
            this.BnfBtnPass.IconPadding = 10;
            this.BnfBtnPass.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BnfBtnPass.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BnfBtnPass.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BnfBtnPass.IconSize = 25;
            this.BnfBtnPass.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.IdleBorderRadius = 35;
            this.BnfBtnPass.IdleBorderThickness = 1;
            this.BnfBtnPass.IdleFillColor = System.Drawing.Color.White;
            this.BnfBtnPass.IdleIconLeftImage = null;
            this.BnfBtnPass.IdleIconRightImage = null;
            this.BnfBtnPass.IndicateFocus = true;
            this.BnfBtnPass.Location = new System.Drawing.Point(832, 70);
            this.BnfBtnPass.Name = "BnfBtnPass";
            this.BnfBtnPass.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnDisabledState.BorderRadius = 35;
            this.BnfBtnPass.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPass.OnDisabledState.BorderThickness = 1;
            this.BnfBtnPass.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPass.OnDisabledState.IconLeftImage = null;
            this.BnfBtnPass.OnDisabledState.IconRightImage = null;
            this.BnfBtnPass.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.onHoverState.BorderRadius = 35;
            this.BnfBtnPass.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPass.onHoverState.BorderThickness = 1;
            this.BnfBtnPass.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPass.onHoverState.IconLeftImage = null;
            this.BnfBtnPass.onHoverState.IconRightImage = null;
            this.BnfBtnPass.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnIdleState.BorderRadius = 35;
            this.BnfBtnPass.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPass.OnIdleState.BorderThickness = 1;
            this.BnfBtnPass.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BnfBtnPass.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnIdleState.IconLeftImage = null;
            this.BnfBtnPass.OnIdleState.IconRightImage = null;
            this.BnfBtnPass.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnPressedState.BorderRadius = 35;
            this.BnfBtnPass.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnPass.OnPressedState.BorderThickness = 1;
            this.BnfBtnPass.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnPass.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnPass.OnPressedState.IconLeftImage = null;
            this.BnfBtnPass.OnPressedState.IconRightImage = null;
            this.BnfBtnPass.Size = new System.Drawing.Size(70, 36);
            this.BnfBtnPass.TabIndex = 4;
            this.BnfBtnPass.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BnfBtnPass.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BnfBtnPass.TextMarginLeft = 0;
            this.BnfBtnPass.TextPadding = new System.Windows.Forms.Padding(0);
            this.BnfBtnPass.UseDefaultRadiusAndThickness = true;
            this.BnfBtnPass.Click += new System.EventHandler(this.BnfBtnPass_Click);
            // 
            // BnfBtnSites
            // 
            this.BnfBtnSites.AllowAnimations = true;
            this.BnfBtnSites.AllowMouseEffects = true;
            this.BnfBtnSites.AllowToggling = true;
            this.BnfBtnSites.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BnfBtnSites.AnimationSpeed = 200;
            this.BnfBtnSites.AutoGenerateColors = false;
            this.BnfBtnSites.AutoRoundBorders = false;
            this.BnfBtnSites.AutoSizeLeftIcon = true;
            this.BnfBtnSites.AutoSizeRightIcon = true;
            this.BnfBtnSites.BackColor = System.Drawing.Color.Transparent;
            this.BnfBtnSites.BackColor1 = System.Drawing.Color.White;
            this.BnfBtnSites.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BnfBtnSites.BackgroundImage")));
            this.BnfBtnSites.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnSites.ButtonText = "Сайты";
            this.BnfBtnSites.ButtonTextMarginLeft = 0;
            this.BnfBtnSites.ColorContrastOnClick = 45;
            this.BnfBtnSites.ColorContrastOnHover = 45;
            this.BnfBtnSites.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = false;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = false;
            borderEdges3.TopRight = true;
            this.BnfBtnSites.CustomizableEdges = borderEdges3;
            this.BnfBtnSites.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BnfBtnSites.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.DisabledForecolor = System.Drawing.Color.White;
            this.BnfBtnSites.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BnfBtnSites.Font = new System.Drawing.Font("Proxima Nova Cn Lt", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.BnfBtnSites.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BnfBtnSites.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BnfBtnSites.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BnfBtnSites.IconMarginLeft = 11;
            this.BnfBtnSites.IconPadding = 10;
            this.BnfBtnSites.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BnfBtnSites.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BnfBtnSites.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BnfBtnSites.IconSize = 25;
            this.BnfBtnSites.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.IdleBorderRadius = 35;
            this.BnfBtnSites.IdleBorderThickness = 1;
            this.BnfBtnSites.IdleFillColor = System.Drawing.Color.White;
            this.BnfBtnSites.IdleIconLeftImage = null;
            this.BnfBtnSites.IdleIconRightImage = null;
            this.BnfBtnSites.IndicateFocus = true;
            this.BnfBtnSites.Location = new System.Drawing.Point(904, 70);
            this.BnfBtnSites.Name = "BnfBtnSites";
            this.BnfBtnSites.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnDisabledState.BorderRadius = 35;
            this.BnfBtnSites.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnSites.OnDisabledState.BorderThickness = 1;
            this.BnfBtnSites.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnSites.OnDisabledState.IconLeftImage = null;
            this.BnfBtnSites.OnDisabledState.IconRightImage = null;
            this.BnfBtnSites.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.onHoverState.BorderRadius = 35;
            this.BnfBtnSites.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnSites.onHoverState.BorderThickness = 1;
            this.BnfBtnSites.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnSites.onHoverState.IconLeftImage = null;
            this.BnfBtnSites.onHoverState.IconRightImage = null;
            this.BnfBtnSites.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnIdleState.BorderRadius = 35;
            this.BnfBtnSites.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnSites.OnIdleState.BorderThickness = 1;
            this.BnfBtnSites.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BnfBtnSites.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnIdleState.IconLeftImage = null;
            this.BnfBtnSites.OnIdleState.IconRightImage = null;
            this.BnfBtnSites.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnPressedState.BorderRadius = 35;
            this.BnfBtnSites.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BnfBtnSites.OnPressedState.BorderThickness = 1;
            this.BnfBtnSites.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.BnfBtnSites.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BnfBtnSites.OnPressedState.IconLeftImage = null;
            this.BnfBtnSites.OnPressedState.IconRightImage = null;
            this.BnfBtnSites.Size = new System.Drawing.Size(70, 36);
            this.BnfBtnSites.TabIndex = 5;
            this.BnfBtnSites.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BnfBtnSites.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BnfBtnSites.TextMarginLeft = 0;
            this.BnfBtnSites.TextPadding = new System.Windows.Forms.Padding(0);
            this.BnfBtnSites.UseDefaultRadiusAndThickness = true;
            this.BnfBtnSites.Click += new System.EventHandler(this.BnfBtnSites_Click);
            this.BnfBtnSites.Leave += new System.EventHandler(this.BnfBtnSites_Leave);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // DGV
            // 
            this.DGV.AllowUserToAddRows = false;
            this.DGV.AllowUserToDeleteRows = false;
            this.DGV.AllowUserToResizeColumns = false;
            this.DGV.AllowUserToResizeRows = false;
            this.DGV.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.DGV.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.DGV.BackgroundColor = System.Drawing.Color.White;
            this.DGV.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DGV.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.DGV.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DGV.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.DGV.ColumnHeadersHeight = 30;
            this.DGV.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DGV.DefaultCellStyle = dataGridViewCellStyle2;
            this.DGV.EnableHeadersVisualStyles = false;
            this.DGV.Location = new System.Drawing.Point(10, 130);
            this.DGV.Name = "DGV";
            this.DGV.ReadOnly = true;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DGV.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.DGV.RowHeadersVisible = false;
            this.DGV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DGV.Size = new System.Drawing.Size(980, 410);
            this.DGV.TabIndex = 6;
            this.DGV.ColumnAdded += new System.Windows.Forms.DataGridViewColumnEventHandler(this.DGV_ColumnAdded);
            this.DGV.ColumnRemoved += new System.Windows.Forms.DataGridViewColumnEventHandler(this.DGV_ColumnRemoved);
            this.DGV.RowsAdded += new System.Windows.Forms.DataGridViewRowsAddedEventHandler(this.DGV_RowsAdded);
            this.DGV.RowsRemoved += new System.Windows.Forms.DataGridViewRowsRemovedEventHandler(this.DGV_RowsRemoved);
            // 
            // lblWelcome
            // 
            this.lblWelcome.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.lblWelcome.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.lblWelcome.Location = new System.Drawing.Point(0, 275);
            this.lblWelcome.Name = "lblWelcome";
            this.lblWelcome.Size = new System.Drawing.Size(1000, 50);
            this.lblWelcome.TabIndex = 39;
            this.lblWelcome.Text = "Добро пожаловать в персональный помошник для сохранения личных данных";
            this.lblWelcome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // bnBtnPassCheck
            // 
            this.bnBtnPassCheck.AllowAnimations = true;
            this.bnBtnPassCheck.AllowMouseEffects = true;
            this.bnBtnPassCheck.AllowToggling = false;
            this.bnBtnPassCheck.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bnBtnPassCheck.AnimationSpeed = 200;
            this.bnBtnPassCheck.AutoGenerateColors = false;
            this.bnBtnPassCheck.AutoRoundBorders = false;
            this.bnBtnPassCheck.AutoSizeLeftIcon = true;
            this.bnBtnPassCheck.AutoSizeRightIcon = true;
            this.bnBtnPassCheck.BackColor = System.Drawing.Color.Transparent;
            this.bnBtnPassCheck.BackColor1 = System.Drawing.Color.White;
            this.bnBtnPassCheck.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bnBtnPassCheck.BackgroundImage")));
            this.bnBtnPassCheck.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnBtnPassCheck.ButtonText = "Как работает сохранение паролей";
            this.bnBtnPassCheck.ButtonTextMarginLeft = 0;
            this.bnBtnPassCheck.ColorContrastOnClick = 45;
            this.bnBtnPassCheck.ColorContrastOnHover = 45;
            this.bnBtnPassCheck.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bnBtnPassCheck.CustomizableEdges = borderEdges5;
            this.bnBtnPassCheck.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bnBtnPassCheck.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.DisabledForecolor = System.Drawing.Color.White;
            this.bnBtnPassCheck.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bnBtnPassCheck.Font = new System.Drawing.Font("Proxima Nova Cn Lt", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bnBtnPassCheck.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bnBtnPassCheck.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bnBtnPassCheck.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bnBtnPassCheck.IconMarginLeft = 11;
            this.bnBtnPassCheck.IconPadding = 10;
            this.bnBtnPassCheck.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bnBtnPassCheck.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bnBtnPassCheck.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bnBtnPassCheck.IconSize = 25;
            this.bnBtnPassCheck.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.IdleBorderRadius = 35;
            this.bnBtnPassCheck.IdleBorderThickness = 1;
            this.bnBtnPassCheck.IdleFillColor = System.Drawing.Color.White;
            this.bnBtnPassCheck.IdleIconLeftImage = null;
            this.bnBtnPassCheck.IdleIconRightImage = null;
            this.bnBtnPassCheck.IndicateFocus = false;
            this.bnBtnPassCheck.Location = new System.Drawing.Point(310, 70);
            this.bnBtnPassCheck.Name = "bnBtnPassCheck";
            this.bnBtnPassCheck.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnDisabledState.BorderRadius = 35;
            this.bnBtnPassCheck.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnBtnPassCheck.OnDisabledState.BorderThickness = 1;
            this.bnBtnPassCheck.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.bnBtnPassCheck.OnDisabledState.IconLeftImage = null;
            this.bnBtnPassCheck.OnDisabledState.IconRightImage = null;
            this.bnBtnPassCheck.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.onHoverState.BorderRadius = 35;
            this.bnBtnPassCheck.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnBtnPassCheck.onHoverState.BorderThickness = 1;
            this.bnBtnPassCheck.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bnBtnPassCheck.onHoverState.IconLeftImage = null;
            this.bnBtnPassCheck.onHoverState.IconRightImage = null;
            this.bnBtnPassCheck.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnIdleState.BorderRadius = 35;
            this.bnBtnPassCheck.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnBtnPassCheck.OnIdleState.BorderThickness = 1;
            this.bnBtnPassCheck.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bnBtnPassCheck.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnIdleState.IconLeftImage = null;
            this.bnBtnPassCheck.OnIdleState.IconRightImage = null;
            this.bnBtnPassCheck.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnPressedState.BorderRadius = 35;
            this.bnBtnPassCheck.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnBtnPassCheck.OnPressedState.BorderThickness = 1;
            this.bnBtnPassCheck.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnBtnPassCheck.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bnBtnPassCheck.OnPressedState.IconLeftImage = null;
            this.bnBtnPassCheck.OnPressedState.IconRightImage = null;
            this.bnBtnPassCheck.Size = new System.Drawing.Size(330, 36);
            this.bnBtnPassCheck.TabIndex = 40;
            this.bnBtnPassCheck.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bnBtnPassCheck.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bnBtnPassCheck.TextMarginLeft = 0;
            this.bnBtnPassCheck.TextPadding = new System.Windows.Forms.Padding(0);
            this.bnBtnPassCheck.UseDefaultRadiusAndThickness = true;
            this.bnBtnPassCheck.Visible = false;
            this.bnBtnPassCheck.Click += new System.EventHandler(this.BnBtnPassCheck_Click);
            // 
            // bnfBtnExit
            // 
            this.bnfBtnExit.AllowAnimations = true;
            this.bnfBtnExit.AllowMouseEffects = true;
            this.bnfBtnExit.AllowToggling = false;
            this.bnfBtnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bnfBtnExit.AnimationSpeed = 200;
            this.bnfBtnExit.AutoGenerateColors = false;
            this.bnfBtnExit.AutoRoundBorders = false;
            this.bnfBtnExit.AutoSizeLeftIcon = true;
            this.bnfBtnExit.AutoSizeRightIcon = true;
            this.bnfBtnExit.BackColor = System.Drawing.Color.Transparent;
            this.bnfBtnExit.BackColor1 = System.Drawing.Color.White;
            this.bnfBtnExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bnfBtnExit.BackgroundImage")));
            this.bnfBtnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnfBtnExit.ButtonText = "Выход";
            this.bnfBtnExit.ButtonTextMarginLeft = 0;
            this.bnfBtnExit.ColorContrastOnClick = 45;
            this.bnfBtnExit.ColorContrastOnHover = 45;
            this.bnfBtnExit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bnfBtnExit.CustomizableEdges = borderEdges4;
            this.bnfBtnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bnfBtnExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.DisabledForecolor = System.Drawing.Color.White;
            this.bnfBtnExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bnfBtnExit.Font = new System.Drawing.Font("Proxima Nova Cn Lt", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bnfBtnExit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bnfBtnExit.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bnfBtnExit.IconLeftPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bnfBtnExit.IconMarginLeft = 11;
            this.bnfBtnExit.IconPadding = 10;
            this.bnfBtnExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bnfBtnExit.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bnfBtnExit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bnfBtnExit.IconSize = 25;
            this.bnfBtnExit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.IdleBorderRadius = 35;
            this.bnfBtnExit.IdleBorderThickness = 1;
            this.bnfBtnExit.IdleFillColor = System.Drawing.Color.White;
            this.bnfBtnExit.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bnfBtnExit.IdleIconLeftImage")));
            this.bnfBtnExit.IdleIconRightImage = null;
            this.bnfBtnExit.IndicateFocus = false;
            this.bnfBtnExit.Location = new System.Drawing.Point(890, 552);
            this.bnfBtnExit.Name = "bnfBtnExit";
            this.bnfBtnExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnDisabledState.BorderRadius = 35;
            this.bnfBtnExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnfBtnExit.OnDisabledState.BorderThickness = 1;
            this.bnfBtnExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.bnfBtnExit.OnDisabledState.IconLeftImage = null;
            this.bnfBtnExit.OnDisabledState.IconRightImage = null;
            this.bnfBtnExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.onHoverState.BorderRadius = 35;
            this.bnfBtnExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnfBtnExit.onHoverState.BorderThickness = 1;
            this.bnfBtnExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bnfBtnExit.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.bnfBtnExit.onHoverState.IconRightImage = null;
            this.bnfBtnExit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnIdleState.BorderRadius = 35;
            this.bnfBtnExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnfBtnExit.OnIdleState.BorderThickness = 1;
            this.bnfBtnExit.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bnfBtnExit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bnfBtnExit.OnIdleState.IconLeftImage")));
            this.bnfBtnExit.OnIdleState.IconRightImage = null;
            this.bnfBtnExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnPressedState.BorderRadius = 35;
            this.bnfBtnExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bnfBtnExit.OnPressedState.BorderThickness = 1;
            this.bnfBtnExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.bnfBtnExit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bnfBtnExit.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.bnfBtnExit.OnPressedState.IconRightImage = null;
            this.bnfBtnExit.Size = new System.Drawing.Size(98, 35);
            this.bnfBtnExit.TabIndex = 41;
            this.bnfBtnExit.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bnfBtnExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bnfBtnExit.TextMarginLeft = 0;
            this.bnfBtnExit.TextPadding = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.bnfBtnExit.UseDefaultRadiusAndThickness = true;
            this.bnfBtnExit.Click += new System.EventHandler(this.BnfBtnExit_Click_1);
            // 
            // txtSearchPass
            // 
            this.txtSearchPass.AcceptsReturn = false;
            this.txtSearchPass.AcceptsTab = false;
            this.txtSearchPass.AnimationSpeed = 200;
            this.txtSearchPass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearchPass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearchPass.BackColor = System.Drawing.Color.Transparent;
            this.txtSearchPass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearchPass.BackgroundImage")));
            this.txtSearchPass.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(16)))), ((int)(((byte)(221)))));
            this.txtSearchPass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearchPass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchPass.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchPass.BorderRadius = 35;
            this.txtSearchPass.BorderThickness = 1;
            this.txtSearchPass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearchPass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchPass.DefaultFont = new System.Drawing.Font("Proxima Nova Cn Lt", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.txtSearchPass.DefaultText = "";
            this.txtSearchPass.FillColor = System.Drawing.Color.White;
            this.txtSearchPass.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            this.txtSearchPass.HideSelection = true;
            this.txtSearchPass.IconLeft = null;
            this.txtSearchPass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchPass.IconPadding = 10;
            this.txtSearchPass.IconRight = null;
            this.txtSearchPass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchPass.Lines = new string[0];
            this.txtSearchPass.Location = new System.Drawing.Point(10, 70);
            this.txtSearchPass.MaxLength = 32767;
            this.txtSearchPass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearchPass.Modified = false;
            this.txtSearchPass.Multiline = false;
            this.txtSearchPass.Name = "txtSearchPass";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(116)))), ((int)(((byte)(204)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchPass.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearchPass.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchPass.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(86)))), ((int)(((byte)(174)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchPass.OnIdleState = stateProperties8;
            this.txtSearchPass.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearchPass.PasswordChar = '\0';
            this.txtSearchPass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchPass.PlaceholderText = "Поиск";
            this.txtSearchPass.ReadOnly = false;
            this.txtSearchPass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearchPass.SelectedText = "";
            this.txtSearchPass.SelectionLength = 0;
            this.txtSearchPass.SelectionStart = 0;
            this.txtSearchPass.ShortcutsEnabled = true;
            this.txtSearchPass.Size = new System.Drawing.Size(260, 40);
            this.txtSearchPass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearchPass.TabIndex = 42;
            this.txtSearchPass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearchPass.TextMarginBottom = 0;
            this.txtSearchPass.TextMarginLeft = 3;
            this.txtSearchPass.TextMarginTop = 0;
            this.txtSearchPass.TextPlaceholder = "Поиск";
            this.txtSearchPass.UseSystemPasswordChar = false;
            this.txtSearchPass.Visible = false;
            this.txtSearchPass.WordWrap = true;
            this.txtSearchPass.TextChange += new System.EventHandler(this.TxtSearchPass_TextChange);
            // 
            // FormSPD
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1000, 600);
            this.Controls.Add(this.txtSearchPass);
            this.Controls.Add(this.bnfBtnExit);
            this.Controls.Add(this.bnBtnPassCheck);
            this.Controls.Add(this.lblWelcome);
            this.Controls.Add(this.DGV);
            this.Controls.Add(this.BnfBtnSites);
            this.Controls.Add(this.BnfBtnPass);
            this.Controls.Add(this.BnfBtnPersData);
            this.Controls.Add(this.txtSearchSite);
            this.Controls.Add(this.bnfGradPnlTitle);
            this.Font = new System.Drawing.Font("Proxima Nova ExCn Rg", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.ForeColor = System.Drawing.Color.Gray;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.KeyPreview = true;
            this.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);
            this.Name = "FormSPD";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormSPD";
            this.Load += new System.EventHandler(this.FormSPD_Load);
            this.bnfGradPnlTitle.ResumeLayout(false);
            this.bnfGradPnlTitle.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DGV)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bnfGradPnlTitle;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button buttonClose;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearchSite;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BnfBtnPersData;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BnfBtnPass;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BnfBtnSites;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.DataGridView DGV;
        public System.Windows.Forms.Label lblUserName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bnBtnPassCheck;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bnfBtnExit;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearchPass;
        public System.Windows.Forms.Label lblWelcome;
    }
}